name: video_auth_app
description: Application vidéo avec authentification Firebase

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  video_player: ^2.9.1
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  google_sign_in: ^6.2.1
  chewie: ^1.7.5
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/ClipWidbo.mp4
    - assets/ClipNatou.mp4
    - assets/ClipPrivat.mp4
    - assets/ClipTanya.mp4
    - assets/Tanya.mp4
    - assets/ClipWidbo.png
    - assets/ClipNatou.png
    - assets/ClipPrivat.png
    - assets/ClipTanya.png
    - assets/Tanya.png
    - assets/9ETAPESPOURCREERUNEAPP.mp4
    - assets/9ETAPESPOURCREERUNEAPP.png
    - assets/ActiverWindows11avieen1minute.mp4
    - assets/ActiverWindows11avieen1minute.png
    - assets/CommentTrouverlaCledeWindows10ou11.mp4
    - assets/CommentTrouverlaCledeWindows10ou11.png
    - assets/InstallerFlutterVSodeGitTutorielFlutterpourdebutants.mp4
    - assets/InstallerFlutterVSodeGitTutorielFlutterpourdebutants.png
    - assets/InstallerFluttersurWindows11en2025GuideCompletavecVSCodeAndroidStu.mp4
    - assets/InstallerFluttersurWindows11en2025GuideCompletavecVSCodeAndroidStu.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon_app.jpg"
